### ISSUE TITLE
Improve Documentation + Examples

### ISSUE THREAD

**Issue by taylorjdawson** [vercel-community/vercel-rust#7]
Unless I am missing something it looks like setting up the project as described in the docs does not warrant a working function. By working I mean that there's now way of invoking the function without specifying the routes in the `now.json` file. If that is the case it could be helpful to others to provide details to setup a complete and working lambda function.

In addition, most rust repos have `example` folder. Maybe adding one here could be helpful as well. It would include everything needed for a working rust lambda function.

Just an idea!

**Comment by mike-engel** [comment]
Hello and thanks for the issue! These docs were mostly copied 1:1 from the old official `@now/rust` docs on ZEIT's builder pages. I'd be more than happy to have PRs submitted if you'd like to add examples or clean up the docs. I can't promise that I'll have time soon to do them myself :)

**Comment by taylorjdawson** [comment]
Cool I'd love to help. Although would you be willing to point me to a working example? I am actually having some trouble setting this up. Specifically with routing. If I use the `Cargo.toml` as an entrypoint is this how routing would look:
```
{
	"version": 2,
	"routes": [{ "src": "/test", "dest": "/src/main.rs" }],
	"builds": [{ "src": "Cargo.toml", "use": "now-rust" }]
}
```

**Comment by mike-engel** [comment]
Ah, I see now. `now-rust` depends on the `name` key in your `Cargo.toml` file for creating the lambdas. So if your crate's name was `test`, you shouldn't need a route at all since `now` would automatically create the lambda at `/test`.

That being said, here are two examples for my `now-rust` projects:

## now-importer
[now.json](https://github.com/mike-engel/now-importer/blob/master/now.json)

You can see here that one `Cargo.toml` file is being targeted as a `src`. The name of that crate is `now_importer_lambda`, which is what is targeted in the `routes` definition. It follows the same directory structure as the `Cargo.toml` file.

## GistCard
[now.json](https://github.com/mike-engel/gistcard/blob/master/now.json)

You can see here again that there are two `Cargo.toml` sources, and those crates are named `gistcard_img` and `gistcard_html`.

Hope that makes sense!

**Comment by taylorjdawson** [comment]
Ohh I see! So if I didn't have any sub folder crates would this be correct for the routing? If I wanted a route to be named different than the crate?

```
[package]
name = "test-api"
version = "0.1.0"
edition = "2018"

[dependencies]
http = "0.1"
now_lambda = "*"

[[bin]]
name = "test-api"
path = "src/main.rs"
```

```
{
	"version": 2,
	"routes": [{ "src": "/api", "dest": "test-api" }],
	"builds": [{ "src": "Cargo.toml", "use": "now-rust" }]
}
```

Thanks for your help!

**Comment by mike-engel** [comment]
I believe that's correct! There's also the alternative `*.rs` entrypoint, which doesn't require as many work-arounds, but requires you to omit `main` and some other things. I'm also not sure you need the `[[bin]]` entry there

**Comment by taylorjdawson** [comment]
Mmm right although if I don't go the `Cargo.toml` route then I get the issues described in #3 but I think that's still being worked on I believe. 

The above config yields a 404 unfortunately.

**Comment by mike-engel** [comment]
@taylorjdawson do you have a repo for the whole project? What does the `source` tab output look like on the now deployment page?

**Comment by taylorjdawson** [comment]
@mike-engel  yeah! Here's [the test repo](https://gitlab.com/taylorjdawson/test-now-rust) I created. I haven't actually tried outside of `now dev` could that be the issue?

**Comment by mike-engel** [comment]
Ahhh yes! That is probably the issue here. It will 404 until you hit the `Cargo.toml` route, at which point it will compile and should be available. Another thing #1 needs to support.

**Comment by taylorjdawson** [comment]
Did it work for you locally using `now dev`?  Once I do `curl -X GET http://localhost:3000/Cargo.toml` it builds but the 2nd time I still get a 404.

**Comment by leerob** [comment]
Closing as stale, I updated the README to make things more clear - and there's examples in the fixtures test folder, too!
